server:
  port: 8080
spring:
  # 数据源相关设置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/novel?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  cache:
    redis:
      time-to-live: 1800000 #缓存存活时间30分钟
  #redis相关设置
  redis:
    port: 6379
    host: localhost
    password: 123456
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
novel:
  cors:
    # 跨域设置
    allow-origins:
      - http://localhost:4048
      - http://localhost:8080
  xss:
    # 过滤开关
    enabled: true
    # 排除链接
    excludes:
      - /system/notice/*
  #JWT秘钥
  jwt:
    secret: 8SDS8JW7DSJ37SAN378SD32KQD7823RFH782892NDF
  file:
    upload:
      path: D:\git_Init\novel_images